// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxcnxnkptbwpcooihxcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4Y254bmtwdGJ3cGNvb2loeGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMjQxNDAsImV4cCI6MjA1NDYwMDE0MH0.rDE5XpKsNbZKlgzG3zNdCvoAWpjfLcEaCmoyDeIj8ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);